#!/bin/bash
apt-get update
apt-get install nginx -y

echo "server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.example.com/destination_page;
    }
}" > /etc/nginx/sites-available/default

service nginx restart

